name: 'rclone Publish'
description: 'Install rclone and publish files/folders to any rclone-supported remote storage backend'

inputs:
  sources:
    description: >
      Comma or newline-separated list of files and/or folders to publish.
      Example: 'dist/,README.md' or one path per line.
      For folders: without trailing slash ('build'), the folder name is appended to remotePath;
      with trailing slash ('build/'), contents are synced directly to remotePath.
    required: true

  recursive:
    description: 'Recursively copy folder contents. When false, only top-level files in folders are copied.'
    required: false
    default: 'true'

  mode:
    description: >
      Transfer mode.
      "sync" (default): one-way mirror — copies source to remote and deletes remote files not in source.
      "copy": additive only — copies source to remote, never deletes anything on the remote.
    required: false
    default: 'sync'

  remoteType:
    description: 'rclone backend type (e.g. sftp, s3, webdav, ftp, local). Required unless rcloneConfig is provided.'
    required: false

  remoteHost:
    description: >
      Remote server address/hostname. Required unless rcloneConfig is provided or remoteType is "local".
      For http/https URLs, any path component is auto-extracted and used as remotePath
      (e.g. "https://cloud.example.com/dav/uploads" sets host to "https://cloud.example.com" and path to "/dav/uploads").
    required: false

  remotePort:
    description: 'Remote server port (optional, uses backend default if omitted).'
    required: false

  remoteUser:
    description: 'Authentication username.'
    required: false

  remotePass:
    description: 'Authentication password (plain-text; auto-obscured by the action). Treat as a secret.'
    required: false

  remotePath:
    description: 'Base path on the remote where files will be published.'
    required: false
    default: '/'

  rcloneConfig:
    description: >
      Raw rclone.conf content. When provided, overrides individual remote* inputs.
      The first remote defined in the config will be used.
    required: false

  rcloneFlags:
    description: 'Extra flags appended to every rclone command (e.g. "--transfers 8 --checkers 16").'
    required: false

  skipCertificateCheck:
    description: 'Skip TLS certificate verification (for self-signed certificates).'
    required: false
    default: 'false'

  include:
    description: >
      Comma or newline-separated list of include filter patterns (e.g. "*.txt, *.log").
      When set, only files matching these patterns are transferred. Follows rclone filter syntax.
      Only applies to directory sources.
    required: false

  exclude:
    description: >
      Comma or newline-separated list of exclude filter patterns (e.g. "*.tmp, .git/**").
      Matching files are skipped during transfer. Follows rclone filter syntax.
      Only applies to directory sources.
    required: false

  deleteExcluded:
    description: 'Delete files on the remote that match exclude filter patterns. Requires exclude to be set.'
    required: false
    default: 'false'

  installRclone:
    description: 'Install rclone if not found on PATH.'
    required: false
    default: 'true'

  rcloneVersion:
    description: 'rclone version to install (e.g. "v1.68.2"). Use "latest" for the newest stable release.'
    required: false
    default: 'latest'

  dryRun:
    description: 'Run rclone with --dry-run (no files are actually transferred).'
    required: false
    default: 'false'

  verbose:
    description: 'Enable verbose logging. Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'

outputs:
  success:
    description: '"true" if all transfers succeeded, "false" otherwise.'

  transferredFiles:
    description: 'Total number of files transferred.'

  rcloneVersion:
    description: 'Installed rclone version string.'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: upload-cloud
  color: blue
